services:
  - type: web
    name: portfolio
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings
