services:
  - type: web
    name: portfolio
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "your-app.onrender.com"
    healthCheckPath: /
    autoDeploy: true
